Repository zangwoo-jeon/news-report-stock-analyzer, pull requests merged in 2025-05, with the labels that each got.

#2 feat : ci.yaml 업로드
  back-end/.github/workflows/ci.yaml
Labels: ✨ feature, 장우

#7 [FEAT] : 회원가입, 회원탈퇴 기능 추가,[FIX] : 예외 처리 파일 수정
  back-end/src/main/java/com/newstoss/global/handler/CustomException.java
  back-end/src/main/java/com/newstoss/global/handler/ErrorCode.java
  back-end/src/main/java/com/newstoss/global/handler/GlobalExceptionHandler.java
  back-end/src/main/java/com/newstoss/global/handler/ResponseErrorEntity.java
  back-end/src/main/java/com/newstoss/global/response/ErrorResponse.java
  back-end/src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
  back-end/src/main/java/com/newstoss/member/adapter/in/web/dto/requestDTO/SignupRequestDTO.java
  back-end/src/main/java/com/newstoss/member/adapter/out/persistence/JPAMemberRepository.java
  back-end/src/main/java/com/newstoss/member/adapter/out/persistence/MemberAdapter.java
  back-end/src/main/java/com/newstoss/member/application/MemberService.java
  back-end/src/main/java/com/newstoss/member/application/command/SignupService.java
  back-end/src/main/java/com/newstoss/member/application/command/WithdrawService.java
  back-end/src/main/java/com/newstoss/member/domain/Member.java
  back-end/src/main/java/com/newstoss/member/domain/MemberCommandPort.java
  back-end/src/main/java/com/newstoss/member/domain/MemberQueryPort.java
  back-end/src/test/java/com/newstoss/member/application/command/SignupServiceTest.java
  back-end/src/test/java/com/newstoss/member/application/command/WithdrawServiceTest.java
Labels: ✨ feature, 준영

#10 fix : ci.yml 파일 수정
  .github/workflows/ci.yml
Labels: 🐛 fix, 장우

#8 Fix: PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🐛 fix, 장우

#13 fix : ci.yml 수정 2
  .github/workflows/ci.yml
Labels: 🐛 fix, 장우

#14 fix : ci 코드 수정 3
  .github/workflows/ci.yml
Labels: 🐛 fix, 장우

#21 [TEST] 테스트 코드 수정
  back-end/src/main/resources/application.yml
  back-end/src/test/java/com/newstoss/member/application/command/SignupServiceTest.java
  back-end/src/test/java/com/newstoss/member/application/command/WithdrawServiceTest.java
Labels: 🧪 test, 준영

#18 [FEAT] 공시정보 캘린더 조회 기능 추가
  .github/workflows/ci.yml
  .idea/.gitignore
  .idea/compiler.xml
  .idea/dbnavigator.xml
  .idea/encodings.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/investinghelper.main.iml
  .idea/news-report-stock-analyzer.iml
  .idea/vcs.xml
  back-end/build.gradle
  back-end/src/main/java/com/newstoss/calender/Calendar.java
  back-end/src/main/java/com/newstoss/calender/CalendarController.java
  back-end/src/main/java/com/newstoss/calender/CalendarRepository.java
  back-end/src/main/java/com/newstoss/calender/CalendarService.java
  back-end/src/main/resources/application-test.yml
  back-end/src/main/resources/application.yml
  back-end/src/test/java/com/newstoss/global/kis/KisTokenTest.java
  back-end/src/test/java/com/newstoss/member/application/command/SignupServiceTest.java
  back-end/src/test/java/com/newstoss/member/application/command/WithdrawServiceTest.java
  postgre.yml
Labels: ✨ feature, 장우
